# Generated by Django 2.1.5 on 2019-02-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190201_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='dm-dashboard'),
            preserve_default=False,
        ),
    ]
